version: '3.8'

services:
  rodin:
    build: .
    ports:
      - "1981:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - COS_SECRET_ID=xxx
      - COS_SECRET_KEY=xxx
      - COS_REGION=ap-guangzhou
      - COS_BUCKET=xxx
